# Introduction

```{r tidyr1, echo = FALSE, message = FALSE, warning = FALSE}

library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=50), tidy = FALSE)

```

# Raptor Population Index

The Raptor Population Index [RPI](https://www.rpi-project.org/) is a collaborative effort to understand and share trends and conservation status of migratory raptors in North America, continent-wide and regionally. Each year thousands of people gather on ridgelines, coastlines, and other concentration points across the globe to watch migrating raptors during the fall and spring. This awe inspiring event provides a fun and accessible point of entry to bird watching and in-flight identification to the public, while also generating decades of standardized monitoring data from sites across North America. These count data also have value for those interested in the status and conservation of raptors.

## Our Mission

The RPI Partnership between Hawk Migration Association of North America (HMANA), HawkWatch International, Hawk Mountain Sanctuary Association, and Birds Canada has a mission to contribute to the conservation, knowledge, and public understanding of raptors and raptor migration through a collaborative population monitoring program that produces conservation assessments and scientifically defensible population trends derived from counts of migrating raptors.

## Objectives

The specific objectives of the Raptor Population Index (RPI) program are to:

-   Produce statistically defensible indices of annual abundance and trends for each species of migratory raptor from as many count sites as possible.

-   Provide frequently updated assessments of the status of each species.

-   Make these results widely available, i.e. to participating count sites, the scientific community, conservation agencies, and the public.

Support for the RPI project has been provided in part by the National Fish and Wildlife Foundation and the U.S. Fish and Wildlife Service, as well as by private donations from HMANA members and friends, and in-kind support from the three partner organizations, HMANA, Hawk Mountain Sanctuary, HawkWatch International, and Birds Canada.

For more information and results, please visit the Raptor Population Index website: <http://www.rpi-project.org/> or NatureCounts: <https://birdscanada.org/birdmon/default/popindices.jsp>

## Author Notes

Version: December 2023
Author: Danielle Ethier, Population Scientist, Birds Canada, dethier@birdscanada.org
