# Methods 

## Count Variables 

In 2023, the trend analysis was changed from using Daily Estimated Total (DET) for all species, to using standardized counts (e.g., banding + census) for Regular Migrants and DETs for all other migration types (defined below). 

You can change the observation count used for the analysis by changing the 'obs.var' value in the "CMMN_Analysis_ParameterValues.csv" file saved in the `Data` folder.  

Note: In the BMDE different column represent different count types. 

ObservationCount =  Daily Estimated Totals
ObservationCount2 = DST
ObservationCount3 = Census
ObservationCount4 = Banded
ObservationCount5 = Other (recap, stopover, repeat)
ObservationCount6 = Other (visual migration, observations outside of census)


## Species classification 

All species at each site are classified using the following describes: 

**M** Regular migrant, 75+% of season covered by station in 2/3 or more of all years, few individuals present before or after clear migratory surge.  Species is well-monitored at the site. Trends are of good quality, and represent change in population size for a large area of the station's catchment area. 

**ML** Similar to M, except that numbers before/after migratory peak (i.e. local area birds) amount to more than a quarter of peak numbers during the migratory surge.  Although the analysis window is limited to the period of migratory surge, the resulting trend is strongly affected by local population level (which may or may not agree with trend for birds migrating through the site).  Note that “local area” birds are those regularly observed at a station, though they may not breed or winter right at the site.

**I** Irruptive and irregular migrants.  For species without a regular pattern of migratory movement, analysis window is usually the whole coverage period, as irruptive timing may vary among years.  Annual indices represent annual variation in extent of irruption (although migration coverage may not cover entire period of movement).  Over the long term population trends may be discernable despite the high degree of annual variation, but should be considered case by case.

**L** Birds from local area (not necessarily breeding or wintering at count site per se, but regularly observed there), showing no migratory peak in seasonal pattern.  Trends are assumed to reflect population change in local area, which may or may not agree with trends at larger scales.

**S** Staging species (usually waterfowl and shorebirds) with pattern of migratory surge of which 75% or more is covered by the station.  Some S species would be M if it were known that movement is unidirectional and there is minimal stopover.  In most cases, however, trends may represent site use rather than population change, as there may be annual variation in use of the specialized stopover sites in the region, only one of which is being monitored.   Trends should be interpreted case by case.

**MX** Regular migrant, but coverage at site a little too short to cover 75% of migration period.   Shifts in timing of migration are not detectable from the data (e.g. change in timing due to climate change could produce a trend that is independent of true population size.)  This is a subclass of "O" species, but designated separately to draw attention to species that could become "M" with modest extension of coverage.

**O** Other. Does not fit into any of the above groups.  May have no clear migratory peak.  May represent individuals of one or a combination of several categories: casual visitors, premigratory dispersal, tail ends of wintering populations, or other classes of birds whose numbers probably do not represent population change either at broad scale or in local breeding population.

## Data filters 

Bad dates: In some cases, certain years or dates are removed from the analysis at a particular site and/or for a particular species at a site. 

The bad dates file can be accessed through the naturecounts R package.

## Abundance filters 

No results are produced for species that do not meet a minimum level of abundance or frequency during the site’s seasonal coverage (average of 10+ detections per season and detected on 5+ days per season). 

## Migration Windows  

Analysis for each species is limited to the dates the species is moving through the site.  Long-term average daily counts were plotted against date, and the analysis “window,” incorporating approximately 95% of the migratory movement, was selected as the dates between which numbers clearly begin to increase and when they return to a relatively steady level following the migratory surge. The same procedure was used for species whose entire migration was not fully covered (i.e., the window omits dates when the species is absent or at low basal levels).  For all species with no clear pattern of movement into and/or out of the area (such as resident species, many “O” species, and irruptive species with irregular timing), the window was defined as the entire seasonal coverage period for that site. 

The [seasonal abundance tool](https://naturecounts.ca/nc/default/popindices.jsp?what=seasonal) allows you to display the migration phenology.  


## Annual Indices and Population Trends 

**To be updated!**

Long-term trends in count were estimated independently for each species, site and season using a Bayesian framework with Integrated Nested Laplace Approximation (R-INLA, Rue et al. 2014).  

We estimated trends using log-linear regression, which included 1) a continuous effect for year (i) to estimate log-linear change in population size over time, 2) first and second order effects for day of year (j) to model the seasonal distribution of counts,  and 3) hierarchical terms to account for random variation in counts among years and among days.  


loga(μ_ij )=〖α+β〗_1×〖year〗_ij+β_2×〖day〗_ij+β_3×〖day〗_ij^2+γ_i+η_j,

where γ_i is a first-order autoregressive (AR1) random effect for year to account for temporal autocorrelation among years, and η_jis an independent and identically distributed (IID) hierarchical term to account for random variation in counts among days of the year.  

For monitoring stations with more than one site (e.g., Long Point Bird Observatory), the regression also included a fixed site effect, as well as interactions between site and the first and second-order day of year effects.

While we recognize that an AR1 random effect for day of year nested within year might have been more appropriate to account for temporal autocorrelation among daily counts, we found that specifying the random day effect as IID had no noticeable effect on trend bias or on probability of estimating a precise trend (probability that the simulated trend fell within confidence limits of the estimated trend; T. L. Crewe, unpublished data).  Specifying the random day effect as IID did, however, significantly increase the speed of analysis, and reduced the probability of errors using INLA.  

We assumed a Poisson distribution of counts, unless the proportion of 0-observation days across years was >= 0.65. This cut-off is somewhat arbitrary, and should be examined in greater detail, but see Crewe et al. 2016. For both data distributions, year estimates and 95% credible intervals were back-transformed to annual rates of population change using 100*exp(estimate)-1.  Trends were calculated using the full dataset, as well as for all 10-year subsets to estimate 10-, 20-, 30-year (etc., where appropriate)  trends for comparison among years over time.  Trends are presented as %/year with lower and upper 95% credible intervals, which suggest that there is a 95% probability that the true trend falls within that range.  A posterior distribution was also calculated to estimate the support for an increasing or declining trend.  A value near 0.5 would suggest equal probability for an increasing and declining trend (little evidence for a change in migration counts over time), whereas a posterior probability near 1 will suggest strong support for the observed change in counts.  The posterior probability can be used as a pseudo p-value, such that trends with a posterior probability > 0.9 could be considered to have strong support.  Annual indices of population size were estimated as the mean daily count from the posterior distribution of the above model. Plots of annual indices show 95% credible intervals (vertical lines), and the black line and grey shading display a loess fit across indices and upper and lower credible intervals.


## Order of execution 

The following outlines the steps taken, in the order taken:

- pick observation count of interest (census, band, DET)
- species loop
- zero-fill
- drop species-specific bad dates
- filter species-specific seasonal windows
- filter out if don't meet minimum year requirement 
- filter abundance (mean # individuals/season/year >= 10)
- filter occurrence (mean # obs days/season/year >= 5)
- drop years with no observations
- generate migration window summary (for plotting online)
- loop through sites (site-specific only) and season, center date variables, and run analysis.
